apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: users-srv
  title: Users Service
  description: A microservice to manage users that have access to various StaffingHQ applications
  annotations:
    github.com/project-slug: Staffing-HQ/users-srv
    backstage.io/techdocs-ref: dir:.
  tags:
    - spring-boot
    - java
    - maven
spec:
  type: service
  owner: group:default/developers
  lifecycle: experimental
  system: users-system
  providesApis:
    - users-srv-api
  dependsOn: ['resource:users-db']
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: users-srv-api
  title: Users Service API
  description: REST API for the Users Service
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/developers
  system: users-system
  definition:
    $text: ./openapi.yaml
